### ISSUE TITLE
Doesn't handle multiple messages having the same `oneof` key

### ISSUE THREAD

**Issue by snoble** [eriktim/elm-protocol-buffers#4]
If you make
```
message Type1 {
  oneof my_options {
    string s = 1;
    int64 i = 2;
  }

message Type2 {
  oneof my_options {
    string s1 = 1;
    string s2 = 2;
  }
}
```
You end up with two declarations of:
```
type MyOptions
    = ...
```

**Comment by maxhille** [comment]
What result would you expect instead?

**Comment by snoble** [comment]
I think following the convention of the library you could prefix with the message name. To preserve backwards compatibility you could only do this only if there’s a collision. The important part is if there’s a naming collision of Types then the elm type checker will detect this as illegal. (I believe it is legal to have a Type name and Variant name collide but I should verify.)

For what it’s worth I think a breaking change wouldn’t bother that many since older projects that use this can pin to an old version and not lose out on much.

**Comment by maxhille** [comment]
Can you prepare a minimal project here on Github which reproduces the problem? If I find time I will take a look at that and try fixing this. Also, I think this is an issue with https://github.com/eriktim/protoc-gen-elm, so it would be great to create an issue there to continue work on it.

**Comment by snoble** [comment]
Sorry, this got lost in my email. I'll create a project next week.

**Comment by eriktim** [comment]
The generator has moved to https://github.com/andreasewering/protoc-gen-elm.
